"use client";
import { useState } from "react";

declare global { interface Window { Razorpay?: new (options: Record<string, unknown>) => { open: () => void }; } }
function loadScript() { return new Promise<void>((resolve, reject) => { if (window.Razorpay) return resolve(); const script = document.createElement("script"); script.src = "https://checkout.razorpay.com/v1/checkout.js"; script.onload = () => resolve(); script.onerror = () => reject(new Error("Checkout could not be loaded.")); document.body.appendChild(script); }); }
export default function ProSubscriptionCheckout({ productCode, className = "" }: { productCode: "pro_monthly" | "pro_annual"; className?: string }) {
  const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false);
  async function start() { if (busy) return; setBusy(true); setStatus("Preparing checkout..."); try { const response = await fetch("/api/billing/razorpay/subscription", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ product_code: productCode }) }); const data = await response.json() as { subscription_id?: string; key_id?: string; display_name?: string; amount?: number; currency?: string; error?: string }; if (!response.ok || !data.subscription_id || !data.key_id) throw new Error(data.error || "Checkout could not be prepared."); await loadScript(); if (!window.Razorpay) throw new Error("Checkout is unavailable."); new window.Razorpay({ key: data.key_id, subscription_id: data.subscription_id, name: "PsyLattice", description: data.display_name, amount: data.amount, currency: data.currency, handler: async (result: Record<string, string>) => { const verified = await fetch("/api/billing/razorpay/subscription/verify", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...result, product_code: productCode }) }); const payload = await verified.json() as { verified?: boolean; error?: string }; setStatus(verified.ok && payload.verified ? "Subscription verified successfully in Test Mode." : (payload.error || "Subscription verification failed.")); setBusy(false); }, modal: { ondismiss: () => { setStatus("Checkout was dismissed."); setBusy(false); } } }).open(); } catch (error) { setStatus(error instanceof Error ? error.message : "Checkout could not be started."); setBusy(false); } }
  return <div className={className}><button type="button" onClick={() => void start()} disabled={busy} className="inline-flex w-full items-center justify-center rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white disabled:opacity-60">{busy ? "Preparing checkout..." : `Get ${productCode === "pro_monthly" ? "Pro Monthly" : "Pro Annual"}`}</button>{status && <p role="status" className="mt-2 text-xs text-slate-500">{status}</p>}</div>;
}
